apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type forward
      port 24223
      bind 0.0.0.0
    </source>

    <match **>
      @type stdout
    </match>