apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-logging-demo
  labels:
    app: golang-logging-demo
  namespace: golang-logging-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-logging-demo
  template:
    metadata:
      labels:
        app: golang-logging-demo
    spec:
      containers:
      - name: golang-logging-demo
        image: dishavirk/golang-logging-demo:v4
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
